### ISSUE TITLE
js and sg_js options are not working

### ISSUE THREAD

**Issue by teles** [drakeh/grunt-styledown#5]
Hello, 

I'm trying to use grunt styledown but I have a small issue.

This is my index.md configuration file:
# Styleguide options
### Body

```
h1 Viva Decora Styleguide
h2 Componentes de css
p Aqui você encontrará os principais componentes de css do Viva Decora, com exemplos de visualização e código html 
div.page-styleguide(sg-content)    
```

and so this is my styledown.js gruntfile:

module.exports = function (grunt, options) {

```
var cssFiles = ['/static/css/vivadecora.min.css', '/static/css/vivastyleguide.min.css'];
var cssFullPathVector;
if(options.vivadecora.is_prod) {
    cssFullPathVector = cssFiles.map(function(e){
        return 'http://vivareal.github.io/vivadecora-v2' + e;
    })
}
else{
    cssFullPathVector =  cssFiles;
}

return {
    build: {
      files: {
        'styleguide/css/index.html': ['static/css/vivadecora.css', 'styleguide/css/index.md']
      },
      options: {
        title: 'Viva Decora Styleguide',
        js: ['https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js'],
        css: cssFullPathVector

      }
    }   
};
```

};

The index.html file is being created with the css correct path, but without the js path.

**Comment by drakeh** [comment]
The problem here is that the `js` and `sg_js` options add JS references to the end of the `<body>` and your styleguide options in `index.md` are overwriting the `<body>` content. See the warning [here](https://github.com/drakeh/grunt-styledown#config). While you are not explicitly using a `config.md` file, you are effectivtely doing so by including styleguide options in your `index.md` file, so the same warning applies.

There are two ways to fix this:
1. Include the JS references in the body template in `index.md`.
2. Remove `index.md` and pass the body template in the Grunt options. You can include any [options supported by the Styledown API](https://github.com/styledown/styledown/blob/master/docs/API.md). Here's what that might look like:

``` js
options: {
  title: 'Viva Decora Styleguide',
  js: ['https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js'],
  css: cssFullPathVector,
  body: '<h1>Viva Decora Styleguide</h1>' + 
        '<h2>Componentes de css</h2>' +
        '<p>Aqui você encontrará os principais componentes de css do Viva Decora, com exemplos de visualização e código html</p>' +
        '<div sg-content></div>'
}
```

Alternatively, if you don't like the HTML in your grunt options, you can stick it in a separate file and pull it in like this:

``` js
body: grunt.file.read("styleguide-body.html")
```

I probably need to expand the documentation around these alternative options. Thanks for bringing this to my attention.

**Comment by teles** [comment]
Thank you for the support, drakeh.
It`s true, my index.md was overwriting the options. I did what you suggested and included the js references on my body element.
Now everything is ok.
Tks

**Comment by drakeh** [comment]
You're welcome. I'm glad you got it working.
